import React from 'react'
import Head from 'next/head'
import styles from "../styles/Layout.module.css";
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';
import Link from 'next/link';

export default function layout({children}) {
  return (
    <div  className={styles.container}>
        <Head>
            <title>Lista de Posts | Next.js</title>
            <meta name="description" content="Generated by create next app" />
        </Head>

        
            <Stack spacing={2} direction="row" alignItems="center" justifyContent="center">
                
              <Link href="/contacto">
                <a>                
                  <Button variant="contained">Contacto</Button>
                </a>
              </Link>

              <Link href="/">
                <a>                
                  <Button variant="contained">Home</Button>
                </a>
              </Link>
              <Link href="/blog">
                <a>                
                  <Button variant="contained">Blog</Button>
                </a>
              </Link>
         
            </Stack>
        
        {children}
        
        <h1>Footer</h1>      
        
    </div>
  )
}
